language: node_js
node_js:
  - node
script:
  - npm test
notifications:
  email: false
deploy:
  provider: heroku
  app: labnode # optional if it's the same as your repo 
  api_key: process.env.API_KEY